#MySQL 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sodamdb
    username: root
    password: 1111
  sql:
    init:
      mode: never
    # alwoys : 항상, embedded : 내장메모지디비, never : 사용안함
  jpa:
    #spring.sql.init
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  # Security Session 시간 설정
  server:
    servlet:
      session:
        timeout: 5s